sudo: false
os:
  - linux
  - osx
language: node_js
before_script:
  - git clone --recursive https://github.com/armory3d/iron_examples
  - git clone --recursive https://github.com/kode/Kha.git iron_examples/cube/Kha
  - git clone https://github.com/kode/nodejs_bin.git iron_examples/cube/nodejs_bin
  - iron_examples/cube/nodejs_bin/copysysbin.sh
script: 
  - cd iron_examples/cube
  - nodejs_bin/node Kha/make.js krom
  - nodejs_bin/node Kha/make.js html5
  - nodejs_bin/node Kha/make.js
  #- nodejs_bin/node Kha/make.js android
