sudo: false
os:
  - linux
  - osx
language: node_js
before_script:
  - git clone --recursive https://github.com/armory3d/iron_examples
  - git clone --recursive https://github.com/kode/Kha.git iron_examples/mesh/Kha
  - git clone https://github.com/kode/nodejs_bin.git iron_examples/mesh/nodejs_bin
  - iron_examples/mesh/nodejs_bin/copysysbin.sh
script: 
  - cd iron_examples/mesh
  - nodejs_bin/node Kha/make.js krom
  - nodejs_bin/node Kha/make.js html5
  #- nodejs_bin/node Kha/make.js windows-hl
  #- nodejs_bin/node Kha/make.js android-native-hl
  #- nodejs_bin/node Kha/make.js ios-hl
